/*
 * File: app/store/Contacts.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3 beta library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3 beta. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Contacts', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Contacts'
    ],

    config: {
        autoLoad: true,
        groupField: 'firstName',
        model: 'MyApp.model.Contacts',
        storeId: 'contacts',
        proxy: {
            type: 'ajax',
            url: 'http://10.200.1.122/touch-2.3.0-beta/touch-2.3.0/examples/blackberry/contacts.json',
            reader: {
                type: 'json'
            }
        },
        sorters: {
            property: 'firstName'
        }
    }
});