/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3 beta library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3 beta. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Main', {
    extend: 'Ext.Container',

    config: {
        activeItem: 1,
        itemId: 'mainContainer',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'freedraw',
                id: 'Edit'
            },
            {
                xtype: 'container',
                id: 'Create',
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'Meeting',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'Title'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        title: 'User',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'Name'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'Share'
            },
            {
                xtype: 'container',
                id: 'Join'
            },
            {
                xtype: 'container',
                id: 'Slides'
            },
            {
                xtype: 'container',
                id: 'Capture'
            },
            {
                xtype: 'container',
                id: 'History'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                hidden: true,
                itemId: 'searchBar',
                items: [
                    {
                        xtype: 'textfield',
                        flex: 1,
                        itemId: 'searchContacts',
                        placeHolder: 'Search Contacts'
                    },
                    {
                        xtype: 'button',
                        action: 'resetSearchbar',
                        text: 'Cancel'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                hidden: false,
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            var main = this.up("[itemId=mainContainer]"),
                                searchBar = main.down("[itemId=searchBar]");

                            searchBar.show();
                        },
                        iconCls: 'search',
                        text: 'Search'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            var main = this.up("[itemId=mainContainer]"),
                                addBar = main.down("[itemId=addBar]");

                            addBar.show();
                        },
                        itemId: 'add',
                        iconCls: 'add',
                        text: 'Add'
                    },
                    {
                        xtype: 'tabmenubutton',
                        menuItems: [
                            {
                                text: 'All',
                                action: 'filterType',
                                filterType: 'all',
                                iconCls: 'view_grid'
                            },
                            {
                                text: 'Favorites',
                                action: 'filterType',
                                filterType: 'favorites',
                                iconCls: 'done'
                            },
                            {
                                text: 'BBM',
                                action: 'filterType',
                                filterType: 'bbm',
                                iconCls: 'bbm'
                            }
                        ],
                        action: 'hideAddBar',
                        docked: 'left',
                        iconCls: 'view_grid'
                    },
                    {
                        xtype: 'overflowmenubutton',
                        menuItems: [
                            {
                                text: 'All',
                                action: 'filterType',
                                filterType: 'all',
                                iconCls: 'view_grid'
                            },
                            {
                                text: 'Favorites',
                                action: 'filterType',
                                filterType: 'favorites',
                                iconCls: 'done'
                            },
                            {
                                text: 'BBM',
                                action: 'filterType',
                                filterType: 'bbm',
                                iconCls: 'bbm'
                            }
                        ],
                        docked: 'right',
                        iconCls: 'overflow_tab'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                hidden: true,
                itemId: 'addBar',
                items: [
                    {
                        xtype: 'textfield',
                        flex: 1,
                        itemId: 'firstName',
                        placeHolder: 'First Name'
                    },
                    {
                        xtype: 'textfield',
                        flex: 1,
                        itemId: 'lastName',
                        placeHolder: 'Last Name'
                    },
                    {
                        xtype: 'button',
                        itemId: 'addContact',
                        text: 'Add'
                    },
                    {
                        xtype: 'button',
                        itemId: 'cancelAdd',
                        text: 'Cancel'
                    }
                ]
            }
        ]
    },

    initialize: function() {
        var me = this;
        
        me.addListener('typefilter', me.filterType, me);
        //me.enableBubble();
        
        //make sure the first list is the default
        me.setActiveItem(0);
        
        me.callParent();
    }

});