/*
 * File: app/view/MyButton5.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3 beta library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3 beta. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyButton5', {
    extend: 'Ext.Button',
    alias: 'widget.mybutton5',

    config: {
        margin: '0 40 0 40',
        maxWidth: 300,
        text: 'Create Meeting'
    }

});