/*
 * File: app/model/Slide.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3 beta library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3 beta. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Slide', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'meeting_id'
            },
            {
                name: 'data'
            },
            {
                name: 'image_url'
            },
            {
                name: 'image_url_tn'
            },
            {
                dateFormat: 'timestamp',
                name: 'created',
                type: 'date'
            }
        ]
    }
});