/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3 beta library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3 beta. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            contactsList: '#contactsList',
            mainContainer: '#mainContainer'
        }
    },

    init: function(application) {
        this.control({
            'button[action=filterType]': {
                tap: this.filterByType
            },
            'button[action=resetSearchbar]': {
                tap: this.resetSearchbar
            },
            'textfield[itemId=searchContacts]': {
                keyup: this.filterByKey
            },
            'button[itemId=addContact]': {
                tap: this.addContact
            },
            'button[itemId=cancelAdd]': {
                tap: this.cancelAdd
            },
            'tabmenubutton[action=hideAddBar]': {
                tap: this.hideAddBar
            }
        
        });
    },

    filterByType: function(button) {
        var me = this,
        	contacts = me.getContactsList(),
            store = contacts.getStore(),
            ftype = button.filterType ? button.filterType : button.config.filterType;
        
        if (ftype === 'all') {
        	store.clearFilter();
        } else {
        	store.filter("type", ftype);
        }
        
        this.hideAddBar();
    },

    hideSearchbar: function() {
        var main = this.getMainContainer(),
        	searchBar = main.down("[itemId=searchBar]");
        
        searchBar.hide();
    },

    resetSearchbar: function() {
        var main = this.getMainContainer(),
            searchField = main.down("textfield");
        
        searchField.setValue();
        this.hideSearchbar();
    },

    filterByKey: function(textfield) {
        var me = this,
        	contacts = me.getContactsList(),
            store = contacts.getStore(),
            value = textfield.getValue();
        
        console.log('dfdfdfdf');
        
        if (value && value.length) {
            var filter = [{
                filterFn: function(record) {
                    var firstName = record.get('firstName').toLowerCase(),
                        lastName = record.get('lastName').toLowerCase();
        
                    if (firstName.match(value) || lastName.match(value)) {
                        return true;
                    }
                    return false;
                }
            }];
            store.filter(filter);
        }
        else {
           store.clearFilter();
        }
    },

    addContact: function(button) {
        var contacts = this.getContactsList(),
            store = contacts.getStore(),
        	firstName = button.up("toolbar").down('[itemId=firstName]'),
            lastName = button.up("toolbar").down('[itemId=lastName]'),
        	msg = 'Your new contact was added!';
        
        if (firstName.getValue() && lastName.getValue()) {
        	store.add({'firstName': firstName.getValue(),'lastName': lastName.getValue(), 'type': 'contacts'});
            firstName.setValue();
            lastName.setValue();
            button.up("toolbar").hide();
        } else {
        	msg = 'Please fill in the required fields!';
        }
        
        Ext.Msg.alert('Notice', msg);
    },

    cancelAdd: function(button) {
        var firstName = button.up("toolbar").down('[itemId=firstName]'),
            lastName = button.up("toolbar").down('[itemId=lastName]');
        
        firstName.setValue();
        lastName.setValue();
        
        this.hideAddBar();
        
        
    },

    hideAddBar: function() {
        var main = this.getMainContainer(),
            addBar = main.down('[itemId=addBar]');
        
        addBar.hide();
    }

});